# Generated by Django 6.0 on 2026-01-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_sql', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
